spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${URL}
        username: ${USERNAME}
        password: ${PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    cloud:
        aws:
            credentials:
                accessKey: ${AWS_ACCESS_KEY}
                secretKey: ${AWS_SECRET_ACCESS_KEY}
            s3:
                bucket: ${BUCKET}
            region:
                static: ${STATIC}
            stack:
                auto: false

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

jwt:
    secret: asdfasdfasdflkasdfjkl
    access_exp: 360000

